version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: erlang_neural
      MYSQL_USER: erlang
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306